- README.md
- docs/dod.md
> Added definition of done

- recommender-front/README.md
- recommender-front/package-lock.json
- recommender-front/package.json
- recommender-front/src/App.js
- recommender-front/src/components/MapComponent.js
- recommender-front/src/components/MapComponent.test.js
- recommender-front/src/index.js
Closes #12 
Adds MapComponent and renders it on the front page.
Adds single front-end test to see MapComponents renders.
Configured package.json to add leaflet-syntax to Jest-tests.
> Rendered map component to app frontend

- recommender-front/Dockerfile
- recommender-front/public/.dockerignore
> Added skeleton for docker

- .github/workflows/docker.yml
- recommender-front/docker-compose.yml
First trial for production setup in Pouta
> Production setup

- recommender-front/src/components/MapComponent.js
- recommender-front/src/components/icon.js
> First POI API implementation

- docs/ci-cd.md
- docs/git-workflow.md
> Clean up docs

- docs/code_quality.md
- docs/hours.md
- recommender-front/package-lock.json
- recommender-front/package.json
- recommender-front/src/components/WeatherComponent.test.jsx
> Added WeatherComponent test and dependencies

- recommender-front/.eslintrc
- recommender-front/package-lock.json
- recommender-front/package.json
- recommender-front/src/App.jsx
I found an improvement for responsive map from React Leaflet documentation:
https://leafletjs.com/examples/mobile/
It is recommended to add meta-data row in to the head of the page:
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
In order to do so I added Helmet Provider library:
https://www.freecodecamp.org/news/react-helmet-examples/ 
Added also title Weather-based Recommender for our App which can be seen in browser tabs and bookmarks.
See #69
> Added HelmetProvider for metadata

- docs/hours.md
- recommender-front/src/App.jsx
- recommender-front/src/assets/style.css
- recommender-front/src/components/header/HeaderComponent.jsx
> Frontend adjustments

- recommender-front/.eslintrc
- recommender-front/src/App.jsx
- recommender-front/src/assets/style.css
- recommender-front/src/components/header/HeaderComponent.jsx
- Zoom works now, I used divs -> next refactoring it to use MUI´s Grid  
- Scroll removed
> Fixed zoom and scroll

- recommender-front/src/App.jsx
- recommender-front/src/assets/style.css
- Refactored divs -> Mui Grids
- Improved the map height
> Improved layout

- recommender-back/poetry.lock
- recommender-back/pyproject.toml
- recommender-back/src/apis/helpers.py
- recommender-back/src/apis/poi.py
- recommender-back/src/apis/time_data.py
Sunrise and set info integrated to poi-scoring. Poi-scoring now takes into account, whether or not the sun is up. If the sun is down, the score is automatically 0.
> Time and sunrise/set info backend

- recommender-front/src/assets/style.css
- Added z-index 9999 for Map component
> Improving the visibility of zoom

- recommender-back/src/apis/helpers.py
- recommender-back/src/apis/poi.py
- recommender-back/src/apis/time_data.py
- recommender-back/src/tests/apis/helpers_test.py
- Fix tests that include poi-scoring by changing the time to a static 12:00 value, which in Helsinki means that the sun is always up all year round. 
- Change time_data.py to not be a class anymore to better align with other modules.
- New parameter "time" for getting pois to support future implementation of timeslider.
> Fix poi-score-tests

- recommender-front/src/components/map/MarkersComponent.jsx
- recommender-front/src/components/map/MarkersComponent.test.jsx
- recommender-front/src/utils/Icon.test.jsx
closes #110 #114 
Tests for frontend/src/utils/icon and frontend/src/components/map/MarkersComponent
Icon test is very small by design, as the icon logic will change.
Needed to disable linter for line 14 in MarkersComponent.test.jsx.
> frontend tests

- recommender-back/src/apis/poi.py
- recommender-back/src/apis/poi_data/sports_and_physical/indoor_sports/sports_halls.json
- recommender-back/src/apis/poi_data/sports_and_physical/outdoor_sports/athletics_venues.json
Added two new categories provided in customer meeting slides.
> Additional categories

- recommender-back/src/apis/time_data.py
- recommender-back/src/apis/weather.py
> added wanted fields to forecast data and fixed the time for fores

- recommender-back/src/apis/current.py
- recommender-back/src/apis/manager.py
- recommender-back/src/apis/poi.py
Latitude and longitude were in the wrong order, and weather data did not show up correctly.
> Fix latitude and longitude

- recommender-back/src/apis/current.py
- recommender-back/src/apis/forecast.py
- recommender-back/src/tests/apis/current_test.py
Added a algorithm to find the missing data for current weather from the nearest weather stations. The algorithm fills every value from it's nearest weather station it can get, and if some values is still missing it finds the missing values from the second nearest tower etc. Fixed tests.
> Fill missing data for current weather

- recommender-back/src/apis/algotunetest.py
- recommender-back/src/apis/current.py
- recommender-back/src/apis/forecast.py
- recommender-back/src/apis/manager.py
- recommender-back/src/apis/poi.py
- recommender-back/src/tests/apis/forecast_test.py
- recommender-back/src/tests/apis/poi_test.py
Changed precipitation from wrong % values to millimeters. Refactored and cleaned some code. Added Docstring. Added error handling for request for the forecast. Secured forecast data searching from forever while-loop if all the stations would have nan value for same value. Changed score to 2 decimal places to show in the frontend.
> Change precipitation values and refactor

- .github/workflows/ci.yml
- README.md
- recommender-back/pyproject.toml
Integrate codecov service to CI workflow.
> Codecov integration

- generate_local_env.sh
- recommender-back/Dockerfile
- recommender-back/pyproject.toml
- recommender-back/src/apis/current.py
- recommender-back/src/apis/forecast.py
- recommender-back/src/apis/manager.py
- recommender-back/src/apis/poi.py
- recommender-back/src/app.py
- recommender-back/src/routes.py
- recommender-back/src/tests/apis/current_test.py
- recommender-back/src/tests/apis/forecast_test.py
- recommender-back/src/tests/apis/poi_test.py
- recommender-back/src/tests/routes_test.py
Switched from relative imports to absolute imports so they work on both Gunicorn and Flask.
Modified generate_local_env.sh to add Pythonpath in case there's trouble running changes locally.
Switched Backend Dockerfile to run Gunicorn instead of Flask (more stable, can run multiple threads etc.)
> Moved backend production to Gunicorn

- recommender-front/src/components/map/MarkersComponent.jsx
- recommender-front/src/components/map/MarkersComponent.test.jsx
Closes [#171](https://github.com/HelsinkiUniCollab/WeatherBasedRecommender/issues/171)
- Added a very basic test for markers component
> Added frontend tests

- recommender-back/src/tests/apis/poi_test.py
Expand tests to cover more code.
> More tests

- codecov.yml
> Small yml fix

- recommender-back/src/apis/forecast.py
- recommender-back/src/app.py
- recommender-back/src/routes.py
Improved get_coordinates() in backend to perform faster.
get_closest_poi_coordinates_data() now uses kd-tree and is super fast (takes under a second now)
> efficiency improvements

- recommender-front/src/assets/style.css
- recommender-front/src/components/header/HeaderComponent.jsx
Adjusted sizing to mobile with a simple @media tag in style.css
- may need some adjustments to fit in screen in all devices/situations correctly
> Added logo to frontend

- recommender-back/src/apis/current.py
- recommender-back/src/apis/forecast.py
- recommender-back/src/config.py
- recommender-back/src/routes.py
- recommender-back/src/services/forecastdatafetcher.py
- recommender-back/src/tests/apis/forecast_test.py
- recommender-back/src/tests/services/forecastdatafetcher_test.py
Separated data download-logic for Forecast class.
Switched to using global variables instead of magic strings.
> Separated some backend logic

- recommender-back/Dockerfile
- recommender-back/src/apis/current.py
- recommender-back/src/apis/forecast.py
- recommender-back/src/config.py
- recommender-back/src/routes.py
- recommender-back/src/services/forecastdatafetcher.py
get_current_airquality was returning an empty dict when latest aqi-values for each stations was nan.
Now it gets latest value that is not nan.
Also did some refactoring that should help with troubleshooting errors.
> refactor aqi fetch

- recommender-front/package-lock.json
- recommender-front/package.json
- recommender-front/src/App.jsx
- recommender-front/src/SimulatorPage.jsx
- recommender-front/src/assets/style.css
- recommender-front/src/components/map/MapComponent.jsx
- recommender-front/src/components/simulator/SimulatorFormComponent.jsx
Frontend components for the simulator in /admin.
Minimal styling etc.
> simulator frontend

- recommender-back/src/routes.py
- recommender-front/src/pages/SimulatorPage.jsx
Minor fixes to simulator front- and backend.
> Simulator fix

- recommender-back/src/routes.py
- recommender-front/src/components/simulator/SimulatorFormComponent.jsx
- recommender-front/src/components/simulator/SimulatorFormComponent.test.jsx
- recommender-front/src/pages/SimulatorPage.jsx
Add input validation for the simulator, error handling for the backend and add same theme as rest of the UI.
> Simulator input validation

- recommender-back/src/apis/poi.py
- recommender-back/src/tests/apis/manager_test.py
- recommender-front/package-lock.json
- recommender-front/package.json
- recommender-front/src/components/simulator/CustomTextField.jsx
- recommender-front/src/components/simulator/SimulatorFormComponent.jsx
- recommender-front/src/components/simulator/SimulatorFormComponent.test.jsx
- recommender-front/src/components/warning/WeatherAlert.jsx
- recommender-front/src/pages/SimulatorPage.jsx
- recommender-front/src/pages/SimulatorPage.test.jsx
Fixed typo in backend that mixed up windspeed and humidity.
New CustomTextField component which SimulatorFormComponent uses.
Input validation (only numbers allowed).
Made form slightly prettier.
Weather warning is shown correctly.
> fixes for simulatorpage

- recommender-front/src/App.jsx
- recommender-front/src/assets/style.css
trying to make all necessary component appear in most common resolutions.
by no means perfect solution but better than last one
- By small heights the map becomes scrollable and watermark may not show.
- What i would like to implement :  sizing that calculates header and fits map to the rest of space at all resolutions.
> fixes to header and watermark visibility

- recommender-front/src/assets/style.css
- recommender-front/src/components/simulator/SimulatorFormComponent.jsx
- recommender-front/src/pages/SimulatorPage.jsx
Moves and resizes a few components to make the sim look a bit better
> Simulator styling

- .github/workflows/cypress.yml
- recommender-front/cypress/e2e/recommender.cy.js
Cypress tests for the simulator page.
> simulator cypress tests

- recommender-back/src/app.py
- recommender-back/src/config.py
For this to work you need to add this line to your backend's local .env file:
CACHE_MODE="simple"
This will make the app use SimpleCache in local development.
> fixed redis not working locally

- recommender-front/src/App.jsx
- recommender-front/src/assets/style.css
- recommender-front/src/components/map/MapComponent.jsx
- should handle also mobile view
> added full screen button to hide header

- README.md
- docker-compose.yaml
- generate_local_env.sh
Updates the script which generates the .env files.
> Update the script

- recommender-back/src/tests/apis/manager_test.py
- recommender-back/src/tests/mock_data.py
- recommender-front/cypress/e2e/recommender.cy.js
- recommender-front/cypress/mockData.js
- recommender-front/src/App.jsx
- recommender-front/src/assets/style.css
- recommender-front/src/components/selector/PreferenceSelector.jsx
- recommender-front/src/components/selector/PreferenceSelector.test.jsx
Selector for filtering pois based on category.
> preference selector + tests

- recommender-front/cypress/e2e/recommender.cy.js
- recommender-front/src/assets/style.css
- recommender-front/src/components/selector/PreferenceSelector.jsx
- Moves the selector under drop down menu so it should now look better on mobile
- Some adjustments to leaflet footer size on on mobile too
> Selector styling

- recommender-back/src/apis/forecast.py
- recommender-back/src/apis/manager.py
- recommender-back/src/app.py
- recommender-back/src/cache_manager.py
- recommender-back/src/routes.py
added cache to store the forecast query time, now aqi is separated from forecast endpoint
> Cache query time and separate aqi from fore

- recommender-back/src/apis/forecast.py
- recommender-back/src/apis/manager.py
- recommender-back/src/app.py
- recommender-back/src/cache_manager.py
- recommender-back/src/routes.py
- recommender-back/src/tests/apis/forecast_test.py
> Separate aqi from fore

- recommender-back/Dockerfile
- recommender-back/src/apis/aqi.py
- recommender-back/src/apis/manager.py
- recommender-back/src/app.py
- recommender-back/src/db/models.py
- recommender-back/src/routes.py
- recommender-back/src/services/poi_init.py
- recommender-back/src/tests/apis/manager_test.py
- recommender-back/src/tests/db/db_test.py
- recommender-back/src/tests/db/models_test.py
- Switched mongo tests to use pois_test collection instead
- Initializes poi collection now on app start (only if its not empty)
- Some bug fixes to aqi
> Mongo and aqi fixes

- recommender-front/cypress/e2e/recommender.cy.js
- recommender-front/src/App.jsx
- recommender-front/src/components/buttons/LocateButton.jsx
- recommender-front/src/components/map/UserLocationComponent.jsx
https was needed for geoloc so this implementation allows us to keep http
> Static loc instead of Geoloc

- recommender-back/src/routes.py
- recommender-front/src/utils/PathComponent.jsx
Can't have a problem with map function if the function doesn't exist lmao. Hopefully this will fix the issue.
> Another pathing fix

- recommender-back/src/apis/manager.py
- recommender-back/src/apis/poi.py
- recommender-back/src/routes.py
- recommender-back/src/services/api_fetcher.py
- recommender-back/src/services/scoring/indoor_scorer.py
- recommender-back/src/services/scoring/outdoor_scorer.py
- recommender-back/src/tests/apis/poi_test.py
- recommender-back/src/tests/services/api_fetcher_test.py
- recommender-back/src/tests/services/scoring/indoor_scorer_test.py
- recommender-back/src/tests/services/scoring/outdoor_scorer_test.py
> moved data fetching

- recommender-back/src/apis/poi.py
- recommender-back/src/tests/apis/manager_test.py
- recommender-front/cypress/e2e/recommender.cy.js
- recommender-front/src/utils/MarkerUtils.jsx
Little UI improvement for Point of Interest popups.
> UI improvement for popup
